### ISSUE TITLE
Example not working: NameError: name 'preprocess_input' is not defined

### ISSUE THREAD

**Issue by Wheele9** [gabrieldemarmiesse/heatmaps#2]
I tried to run your code found on the 'front' page.
Things started well:

Model type detected: local pooling - flatten
Model cut at layer: 18
Pool size infered: 7

But then I got an error:
```
--------------------------------------------------
NameError        Traceback (most recent call last)
<ipython-input-3-1c2ccf5b77eb> in <module>()
     27 model = VGG16()
     28 new_model = to_heatmap(model)
---> 29 display_heatmap(new_model, "pics/dog.jpg")

<ipython-input-3-1c2ccf5b77eb> in display_heatmap(new_model, img_path)
     15     x = image.img_to_array(img)
     16     x = np.expand_dims(x, axis=0)
---> 17     x = preprocess_input(x)
     18 
     19     out = new_model.predict(x)

NameError: name 'preprocess_input' is not defined
```

Can you help me with this? I am using theano 0.9, keras 1.2.2

**Comment by gabrieldemarmiesse** [comment]
Hi!

Thanks for noticing the error, I forgot an import line:

`from keras.applications.imagenet_utils import preprocess_input`
 
This is when using the VGG16/VGG19/ResNet50

If you use Inception_V3 or XCeption, use:

from keras.applications.inception_v3 import preprocess_input

I'll change the front page ASAP.

Cheers,
Gabriel

**Comment by Wheele9** [comment]
Thank you, it solved my problem. I ran into anther issue,. I got StopIterationError:

```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-60-a02f1ca343b3> in <module>()
----> 1 display_heatmap(new_model, "pics/pigs2.jpg", 'human')

<ipython-input-58-60e33d3211ed> in display_heatmap(model, img_path, classe)
     14     s = name2ID[classe]
     15     print (s)
---> 16     ids = synset_to_dfs_ids(s)
     17 
     18     heatmap_dog = out[0,ids].sum(axis=0)

/media/matyi/Data/kaggle/reTrainVgg16/heatmap.py in synset_to_dfs_ids(synset)
     50 # This is to find all the outputs that correspond to the class we want.
     51 def synset_to_dfs_ids(synset):
---> 52     ids = [x for x in depthfirstsearch(synset) if x <= 1000]
     53     ids = [corr[x] for x in ids]
     54     return ids

/media/matyi/Data/kaggle/reTrainVgg16/heatmap.py in depthfirstsearch(id_, out)
     40         pass
     41     else:
---> 42         id_ = next(int(s[0]) for s in synsets if s[1][0] == id_)
     43 
     44     out.append(id_)

StopIteration: 

```

I used the example at the front page, I just added a 3rd argument to the display_heatmap() function, which is a class. If the class is human (n02472987). I got the error above, if it is pig (n02395406) or dog, it works just fine. Here is my 'full' code:

```
name2ID ={'dog':'n02084071',
        'hog' : 'n02395406',
        'human' : 'n02472987'}

def display_heatmap(model, img_path, classe='hog'):

    # the only difference to your example
    s = name2ID[classe]



display_heatmap(new_model, "pics/dog33.jpeg", 'human')
```

Do you have any idea why this occurs?

**Comment by gabrieldemarmiesse** [comment]
Since this part of the code to find output indexes to keep was taken from the heuritech repo, I haven't looked into it much. I'll see if I can fix it. A temporary fix to get your project going could be this one: If you want certain classes, you can manually find them on this page : https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a
It's a bit long but it's a temporary fix (hopefully I can find the bug). In your case, you're looking for humans, there only seem to have one of the 1000 categories that is for humans, it's 981: 'ballplayer, baseball player'.

So in your code, you can put
`ids = [981]`
It should solve the issue partially. But I think the bigger picture here is that there doesn't seem that neural networks trained on imagenet are good at recognizing humans since it's not represented much in the 1000 categories.

**Comment by Wheele9** [comment]
I got my synset for the human class from this site: [http://image-net.org/synset?wnid=n02472293](http://image-net.org/synset?wnid=n02472293)
Which is the recommended way to get new classes in the heuritics repo. I did'nt have much time either, but I start  too see, that we can not use all synset available at image-net.org, only the ones found in [https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a](https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a)

**Comment by gabrieldemarmiesse** [comment]
If it solves your problem, please close the issue. Thanks again for noticing an import was missing.

cheers,
Gabriel
