### ISSUE TITLE
sigmoid outputs?

### ISSUE THREAD

**Issue by ahundt** [gabrieldemarmiesse/heatmaps#6]
Hey, this looks nice! Is there any chance I can get a heatmap for 1 (and more) sigmoid outputs?

**Comment by gabrieldemarmiesse** [comment]
Hi! Thanks! 

Yes, it should work out with a sigmoid output. The `to_heatmap` function will print some information, you'll be able to check then that it detected the correct output activation.

**Comment by gabrieldemarmiesse** [comment]
Closing this. Feel free to reopen if something isn't clear.
