### ISSUE TITLE
why must you replace softmax by softmax4D

### ISSUE THREAD

**Issue by JaspervDalen** [gabrieldemarmiesse/heatmaps#9]
You replace softmax with softmax4D (mobilenet) but why? What is the difference and how can I still get the correct prediction from this layer?
The softmax4D Change changes the heatmaps for the first two classes to the heatmap of the 3rd (final) class made using the normal softmax layer and the one of the final layer (that is also the prediction in this example) to something less logical

**Comment by gabrieldemarmiesse** [comment]
The softmax is applied along the channels axis, pixelwise, so in the end, it's similar to do one classification per pixel, and grouping the result to provide one heatmap per class. This approach works well on examples that I've shown on the readme. And can be also think of, as a classification network applied as a sliding window on the input image.

**Comment by gabrieldemarmiesse** [comment]
I'll close this issue. Feel free to reopen it if necessary.
